# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

spring:
  main:
    banner-mode: "off"
  application:
    name: "oppivelvollisuus-service"
  flyway:
    # Flyway is run manually by shared/config/DatabaseConfig
    enabled: false
  sql:
    init:
      continue-on-error: false
      encoding: "UTF-8"
