// SPDX-FileCopyrightText: 2023-2024 City of Espoo
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package fi.espoo.oppivelvollisuus.domain

import ch.qos.logback.classic.Logger
import ch.qos.logback.classic.spi.ILoggingEvent
import ch.qos.logback.core.read.ListAppender
import fi.espoo.oppivelvollisuus.FullApplicationTest
import fi.espoo.oppivelvollisuus.TestHttpClient
import fi.espoo.oppivelvollisuus.makeTestToken
import minimalStudentAndCaseTestInput
import minimalStudentCaseTestInput
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Autowired
import testUser
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Locks in audit log emission behavior.
 *
 * Audit events are emitted via the AUDIT_EVENT marker at WARN level by the
 * shared/Audit.kt enum's `log()` method. The structured arguments include
 * eventCode, targetId, objectId, securityLevel, securityEvent, plus optional meta.
 *
 * The userId is NOT in the structured arguments — it is set on MDC by
 * `RequestToAuthenticatedUser` (only on real HTTP requests). The MDC test below
 * exercises that path explicitly.
 */
class AuditLogTests : FullApplicationTest(resetDbBeforeEach = true) {
    @Autowired private lateinit var controller: AppController

    private val listAppender = ListAppender<ILoggingEvent>()

    // Attach to the root logger to capture all loggers (including AppController's)
    private val rootLogger = LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME) as Logger

    @BeforeEach
    fun attachAppender() {
        // Clear any events accumulated from previous tests (shared instance, PER_CLASS lifecycle)
        listAppender.list.clear()
        if (!listAppender.isStarted) {
            listAppender.start()
        }
        rootLogger.addAppender(listAppender)
    }

    @AfterEach
    fun detachAppender() {
        rootLogger.detachAppender(listAppender)
    }

    private fun auditEvents(): List<ILoggingEvent> =
        listAppender.list.filter { event ->
            event.markerList?.any { it.name == "AUDIT_EVENT" } == true
        }

    // -------------------------------------------------------------------------
    // CREATE_STUDENT emits an audit event
    // -------------------------------------------------------------------------

    @Test
    fun `createStudent emits CREATE_STUDENT audit event`() {
        controller.createStudent(testUser, minimalStudentAndCaseTestInput, dbInstance())

        val events = auditEvents()
        assertTrue(events.isNotEmpty(), "Expected at least one AUDIT_EVENT marker log, got none")

        val createEvent = events.find { it.message == "CREATE_STUDENT" }
        assertNotNull(createEvent, "Expected CREATE_STUDENT audit event, got: ${events.map { it.message }}")
    }

    @Test
    fun `createStudent audit event uses WARN level`() {
        controller.createStudent(testUser, minimalStudentAndCaseTestInput, dbInstance())

        val event =
            auditEvents().find { it.message == "CREATE_STUDENT" }
                ?: error("No CREATE_STUDENT event found")

        assertEquals(
            ch.qos.logback.classic.Level.WARN,
            event.level,
            "Audit events must be logged at WARN level"
        )
    }

    @Test
    fun `createStudent audit event has AUDIT_EVENT marker`() {
        controller.createStudent(testUser, minimalStudentAndCaseTestInput, dbInstance())

        val event =
            auditEvents().find { it.message == "CREATE_STUDENT" }
                ?: error("No CREATE_STUDENT event found")

        assertTrue(
            event.markerList?.any { it.name == "AUDIT_EVENT" } == true,
            "Audit event must have AUDIT_EVENT marker"
        )
    }

    // -------------------------------------------------------------------------
    // UPDATE_STUDENT_CASE emits an audit event with caseId in meta
    // -------------------------------------------------------------------------

    @Test
    fun `updateStudentCase emits UPDATE_STUDENT_CASE audit event with caseId`() {
        val studentId = controller.createStudent(testUser, minimalStudentAndCaseTestInput, dbInstance())
        val caseId =
            controller
                .getStudent(testUser, studentId, dbInstance())
                .cases
                .first()
                .id

        // Clear events generated by setup calls
        listAppender.list.clear()

        controller.updateStudentCase(testUser, studentId, caseId, minimalStudentCaseTestInput, dbInstance())

        val events = auditEvents()
        val updateEvent = events.find { it.message == "UPDATE_STUDENT_CASE" }
        assertNotNull(updateEvent, "Expected UPDATE_STUDENT_CASE audit event, got: ${events.map { it.message }}")

        // caseId and studentId must appear in the structured arguments (meta map)
        val argString = updateEvent.argumentArray?.joinToString(" ") { it.toString() } ?: ""
        assertTrue(
            argString.contains(caseId.toString()),
            "Expected caseId $caseId in audit event arguments: $argString"
        )
        assertTrue(
            argString.contains(studentId.toString()),
            "Expected studentId $studentId in audit event arguments: $argString"
        )
    }

    // -------------------------------------------------------------------------
    // Logger name is the shared Audit file (Audit.kt) — events flow through
    // Audit.X.log() rather than each controller's own logger
    // -------------------------------------------------------------------------

    @Test
    fun `audit event logger name is the shared Audit file`() {
        controller.createStudent(testUser, minimalStudentAndCaseTestInput, dbInstance())

        val event =
            auditEvents().find { it.message == "CREATE_STUDENT" }
                ?: error("No CREATE_STUDENT event found")

        assertEquals(
            "fi.espoo.oppivelvollisuus.shared.Audit",
            event.loggerName,
            "Audit logger name must be the shared Audit enum"
        )
    }

    // -------------------------------------------------------------------------
    // userId reaches the audit event via MDC, set by RequestToAuthenticatedUser
    // (only when going through the actual HTTP filter chain)
    // -------------------------------------------------------------------------

    @Test
    fun `audit event carries userId via MDC when triggered through HTTP`() {
        val client = TestHttpClient(httpPort)
        val token = makeTestToken(testUser.id.raw.toString())

        val response = client.get("/employees", token = token)
        assertEquals(200, response.statusCode, "GET /employees must succeed")

        val event =
            auditEvents().find { it.message == "GET_EMPLOYEES" }
                ?: error("No GET_EMPLOYEES audit event was captured")

        assertEquals(
            testUser.id.raw.toString(),
            event.mdcPropertyMap["userId"],
            "Audit event must carry userId from MDC when emitted during an HTTP request"
        )
    }

    // -------------------------------------------------------------------------
    // Non-mutation endpoint also emits audit
    // -------------------------------------------------------------------------

    @Test
    fun `getEmployeeUsers emits GET_EMPLOYEES audit event`() {
        controller.getEmployeeUsers(testUser, dbInstance())

        val events = auditEvents()
        assertNotNull(
            events.find { it.message == "GET_EMPLOYEES" },
            "Expected GET_EMPLOYEES audit event, got: ${events.map { it.message }}"
        )
    }

    // -------------------------------------------------------------------------
    // No audit events before any controller call
    // -------------------------------------------------------------------------

    @Test
    fun `no spurious audit events are emitted without controller calls`() {
        val events = auditEvents()
        assertTrue(events.isEmpty(), "Expected no audit events, got: ${events.map { it.message }}")
    }
}
